### ISSUE TITLE
Issue with autoplay

### ISSUE THREAD

**Issue by Rajesh1041** [curiouslearning/CuriousReaderInteractiveFunctionsH5P#23]

**Comment by burrage** [comment]
I believe this is because timestamps aren't being saved after creating a Curious Reader Audio object. When you go back and edit the Curious Reader Audio object, all the timestamps are missing.

Temporary fix: if you have saved the timestamps to a text file, choose to edit the Curious Reader Audio object and place the timestamps in manually and press save.

**Comment by burrage** [comment]
More info... it looks like timestamps that AREN'T manually typed in by the user aren't saved. That is, all values that are put in as the result of using the waveform editor don't actually save.
